name: Test versions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [
          macos-15, 
          macos-15-intel,
          ubuntu-latest, 
          ubuntu-22.04-arm
        ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
        if: ${{ runner.os == 'Linux' }}

      - name: Install tap
        if: matrix.os != 'macos-15'
        run: |
          brew tap pact-foundation/tap
          cd $(brew --prefix)/Homebrew/Library/Taps/pact-foundation/homebrew-tap/
          git checkout ${{ github.event.pull_request.head.sha || github.sha }}
          brew install --verbose --debug pact pact-stub-server pact-plugin pact-mock-server pact-verifier pact-broker-client pact-legacy

      - name: Install tap
        if: matrix.os == 'macos-15'
        run: |
          brew tap pact-foundation/tap
          cd $(brew --prefix)/Library/Taps/pact-foundation/homebrew-tap/
          git checkout ${{ github.event.pull_request.head.sha || github.sha }}
          brew install --verbose --debug pact pact-stub-server pact-plugin pact-mock-server pact-verifier pact-broker-client pact-legacy

      - name: Brew test tap
        run: |
          brew test pact pact-stub-server pact-plugin pact-mock-server pact-verifier pact-legacy pact-broker-client --verbose --debug

      - name: Audit tap
        run: |
          brew audit --strict --online pact pact-stub-server pact-plugin pact-mock-server pact-verifier pact-broker-client pact-legacy
